### Send the lab-based.csv file to our upload server
POST http://localhost:8080/v1/upload HTTP/1.1
Content-Type: multipart/form-data; boundary=----WebKitFormBoundary7MA4YWxkTrZu0gW

------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="experiment"
Content-Type: text/plain

lab-based-clean
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="date"
Content-Type: text/plain

March 22, 2024
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="location"
Content-Type: text/plain

SFU
------WebKitFormBoundary7MA4YWxkTrZu0gW
Content-Disposition: form-data; name="file"; filename="lab-based-clean.csv"
Content-Type: text/csv

< ./lab-based-clean.csv
------WebKitFormBoundary7MA4YWxkTrZu0gW--
###
GET http://localhost:8080/v1/health HTTP/1.1
###
GET http://localhost:8080/v1/experiment/lab HTTP/1.1
