# syntax=docker/dockerfile:1

FROM golang:1.23.3 AS build

WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .

RUN CGO_ENABLED=0 GOOS=linux go build -o /docker-truthiness

FROM build AS run-test
RUN go test -v ./...

FROM gcr.io/distroless/base-debian11 AS build-release

WORKDIR /

COPY --from=build /docker-truthiness /docker-truthiness

EXPOSE 8080

USER nonroot:nonroot

ENTRYPOINT ["/docker-truthiness"]